### ISSUE TITLE
README

### ISSUE THREAD

**Issue by RobertASmith** [dark-peak-analytics/unmet-needs#7]
Could you please improve the README along the lines of this one: https://github.com/dark-peak-analytics/who_decide_AP but with the dark-peak-analytics logo rather than the bolster one. 

At the bottom of the readme should be your DPA email so that if people are interested they can contact you, and also the link to our website.

**Comment by W-Mohammed** [comment]
- [ ] Done!

@RobertASmith, please check the readme file and let me know what you think!

**Comment by RobertASmith** [comment]
Looks good, feel free to submit a pull request to main.

**Comment by W-Mohammed** [comment]
I waiting for Richard's "About the tool" text to add to the branch before we push to **main**.
