### ISSUE TITLE
Dev into Main please

### ISSUE THREAD

**Issue by RobertASmith** [dark-peak-analytics/unmet-needs#8]
Hi @W-Mohammed this project looks stable now, can we merge `dev` into `main` ?

**Comment by W-Mohammed** [comment]
Hi @RobertASmith,

Yes, it is relatively stable. However, I await final confirmation and feedback from Richard Cookson before I merge `dev` to `main`.

**Comment by RobertASmith** [comment]
Ahh OK fair enough - could you copy over the readme for now, just in case
people are curious.

**Comment by W-Mohammed** [comment]
Done!

**Comment by RobertASmith** [comment]
Thanks so much
